<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BankSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $banks = [
            "014" => "Bank BCA (Bank Central Asia)",
            "008" => "Bank Mandiri",
            "009" => "Bank BNI (Bank Negara Indonesia)",
            "427" => "Bank Syariah Indonesia (Eks BNI SYARIAH)",
            "002" => "Bank BRI (Bank Rakyat Indonesia)",
            "451" => "Bank Syariah Indonesia (Eks BSM)",
            "022" => "Bank CIMB Niaga",
            "022" => "Bank CIMB Niaga Syariah",
            "147" => "Bank Muamalat",
            "213" => "Bank BTPN (Bank Tabungan Pensiunan Nasional)",
            "547" => "Bank BTPN Syariah",
            "213" => "Jenius",
            "422" => "Bank Syariah Indonesia (Eks BRI Syariah)",
            "200" => "Bank Tabungan Negara (Bank BTN)",
            "013" => "Permata Bank",
            "011" => "Bank Danamon",
            "016" => "Bank BII Maybank",
            "426" => "Bank Mega",
            "153" => "Bank Sinar Mas",
            "950" => "Bank Commonwealth",
            "028" => "Bank OCBC NISP",
            "441" => "Bank KB Bukopin",
            "521" => "Bank KB Bukopin Syariah",
            "536" => "Bank BCA Syariah",
            "026" => "Bank Lippo",
            "031" => "Citibank",
            "789" => "Indosat Dompetku",
            "911" => "Telkomsel Tcash",
            "911" => "LinkAja",
            "046" => "Bank DBS Indonesia",
            "046" => "Digibank",
            "535" => "SeaBank (Eks Bank Kesejahteraan Ekonomi)",
            "542" => "Bank Jago (Eks Bank Artos Indonesia)",
            "023" => "Bank UOB Indonesia",
            "023" => "TMRW by UOB Indonesia",
            "490" => "Bank Neo Commerce (Akulaku)",
            "567" => "Allo Bank (Eks Bank Harda)",
            "947" => "Bank Aladin Syariah (Eks Bank Maybank Indocorp)",

            "110" => "Bank Jabar dan Banten (Bank BJB)",
            "111" => "Bank DKI Jakarta",
            "112" => "BPD DIY (Yogyakarta)",
            "113" => "Bank JATENG (Jawa Tengah)",
            "114" => "Bank JATIM (Jawa Timur)",
            "115" => "Bank Jambi",
            "116" => "BPD Aceh",
            "116" => "BPD Aceh Syariah",
            "117" => "Bank SUMUT (Sumatra Utara)",
            "118" => "Bank NAGARI (Bank SUMBAR)",
            "119" => "Bank Riau Kepri",
            "120" => "Bank SUMSEL BABEL",
            "121" => "Bank Lampung",
            "122" => "Bank KALSEL (Bank Kalimantan Selatan)",
            "123" => "Bank KALBAR (Bank Kalimantan Barat)",
            "124" => "Bank KALTIMTARA (Bank Kalimantan Timur dan Utara)",
            "125" => "Bank KALTENG (Bank Kalimantan Tengah)",
            "126" => "Bank SULSELBAR (Bank Sulawesi Selatan dan Barat)",
            "127" => "Bank SULUTGO (Bank Sulawesi Utara dan Gorontalo)",
            "128" => "Bank NTB",
            "128" => "Bank NTB Syariah",
            "129" => "Bank BPD Bali",
            "130" => "Bank NTT",
            "131" => "Bank Maluku MALUT",
            "132" => "Bank PAPUA",
            "133" => "Bank Bengkulu",
            "134" => "Bank SULTENG (Bank Sulawesi Tengah)",
            "135" => "Bank SULTRA",
            "137" => "Bank BPD Banten",

            "003" => "Bank Ekspor Indonesia",
            "019" => "Bank Panin",
            "517" => "Bank Panin Dubai Syariah",
            "020" => "Bank Arta Niaga Kencana",
            "030" => "American Express Bank LTD",
            "031" => "Citibank N.A.",
            "032" => "JP. Morgan Chase Bank, N.A.",
            "033" => "Bank of America, N.A",
            "034" => "Ing Indonesia Bank",
            "036" => "Bank Multicor",
            "037" => "Bank Artha Graha Internasional",
            "039" => "Bank Credit Agricole Indosuez",
            "040" => "The Bangkok Bank Comp. LTD",
            "087" => "Bank HSBC Indonesia",
            "042" => "Mitsubishi UFJ Financial Group (MUFG Bank)",
            "045" => "Bank Sumitomo Mitsui Indonesia",
            "047" => "Bank Resona Perdania",
            "048" => "Bank Mizuho Indonesia",
            "050" => "Standard Chartered Bank",
            "052" => "Bank ABN AMRO",
            "053" => "Bank Keppel Tatlee Buana",
            "054" => "Bank Capital Indonesia",
            "057" => "Bank BNP Paribas Indonesia",
            "059" => "Korea Exchange Bank Danamon",
            "060" => "RABOBANK Internasional Indonesia",
            "061" => "Bank ANZ Indonesia",
            "212" => "Bank Woori Saudara",
            "069" => "Bank of China",
            "076" => "Bank Bumi Arta",
            "087" => "Bank HSBC Indonesia (Eks. Bank Ekonomi)",
            "088" => "Bank AntarDaerah",
            "089" => "Bank Haga",
            "093" => "Bank IFI",
            "095" => "Bank J Trust Indonesia",
            "097" => "Bank Mayapada",
            "145" => "Bank Nusantara Parahyangan",
            "146" => "Bank Swadesi (Bank of India Indonesia)",
            "151" => "Bank Mestika Dharma",
            "152" => "Bank SHINHAN Indonesia (Bank Metro Express)",
            "157" => "Bank Maspion Indonesia",
            "159" => "Bank Hagakita",
            "161" => "Bank Ganesha",
            "162" => "Bank Windu Kentjana",
            "164" => "Bank ICBC Indonesia (Halim Indonesia Bank)",
            "166" => "Bank Harmoni International",
            "167" => "Bank QNB Kesawan (Bank QNB Indonesia)",
            "212" => "Bank Himpunan Saudara 1906",
            "405" => "Bank Swaguna",
            "459" => "Krom Bank (Eks. Bank Bisnis Internasional)",
            "466" => "Bank Sri Partha",
            "472" => "Bank Jasa Jakarta",
            "484" => "Bank Hana (Eks. Bank Bintang Manunggal)",
            "485" => "Bank MNC Internasional (Bank Bumiputera)",
            "490" => "Bank Yudha Bhakti",
            "491" => "Bank Mitraniaga",
            "494" => "Bank Raya (BRI Agro Niaga)",
            "498" => "Bank SBI Indonesia (Bank Indomonex)",
            "501" => "Bank Royal Indonesia",
            "503" => "Bank National Nobu (Bank Alfindo)",
            "506" => "Bank Mega Syariah",
            "513" => "Bank Ina Perdana",
            "517" => "Bank Harfa",
            "520" => "Prima Master Bank",
            "521" => "Bank Persyarikatan Indonesia",
            "525" => "Bank Akita",
            "526" => "Bank Oke Indonesia (Liman International Bank)",
            "531" => "Anglomas Internasional Bank",
            "523" => "Bank Sahabat Sampoerna (Bank Dipo International)",
            "547" => "Bank Purba Danarta",
            "548" => "Bank Multi Arta Sentosa",
            "553" => "Bank Mayora Indonesia",
            "555" => "Bank Index Selindo",
            "566" => "Bank Victoria International",
            "558" => "Bank Eksekutif",
            "559" => "Centratama Nasional Bank",
            "562" => "Bank Fama Internasional",
            "564" => "Bank Mandiri Taspen Pos (Bank Sinar Harapan Bali)",
            "945" => "Bank Agris (Bank Finconesia)",
            "946" => "Bank Merincorp",
            "949" => "Bank CTBC (China Trust) Indonesia",
            "425" => "Bank BJB Syariah",
            "688" => "BPR KS (Karyajatnika Sedaya)",
            "600" => "BPR Supra Artapersada",
            "028" => "BPR Danagung Abadi",
            "028" => "BPR Danagung Bakti",
            "028" => "BPR Danagung Ramulti",
            "945" => "Bank IBK Indonesia",
        ];

        foreach ($banks as $code => $name) {
            DB::table('banks')->insert([
                'name' => $name,
                'code' => $code,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
