<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProviderSeeder extends Seeder
{
    public function run()
    {
        $banks = [
            "014" => "Bank BCA (Bank Central Asia)",
            "008" => "Bank Mandiri",
            "009" => "Bank BNI (Bank Negara Indonesia)",
            "427" => "Bank Syariah Indonesia",
            "002" => "Bank BRI (Bank Rakyat Indonesia)",
            "451" => "Bank Syariah Indonesia (Eks BSM)",
            "022" => "Bank CIMB Niaga",
            "147" => "Bank Muamalat",
            "213" => "Bank BTPN",
            "547" => "Bank BTPN Syariah",
            "422" => "Bank Syariah Indonesia",
            "200" => "Bank BTN (Bank Tabungan Negara)",
            "013" => "Permata Bank",
            "011" => "Bank Danamon",
            "016" => "Bank Maybank Indonesia",
            "426" => "Bank Mega",
            "153" => "Bank Sinar Mas",
            "950" => "Bank Commonwealth",
            "028" => "Bank OCBC NISP",
            "441" => "Bank KB Bukopin",
            "521" => "Bank KB Bukopin Syariah",
            "536" => "Bank BCA Syariah",
            "026" => "Bank Lippo",
            "031" => "Citibank N.A.",
            "046" => "Bank DBS Indonesia",
            "535" => "SeaBank",
            "542" => "Bank Jago",
            "023" => "Bank UOB Indonesia",
            "490" => "Bank Neo Commerce",
            "567" => "Allo Bank",
            "947" => "Bank Aladin Syariah",

            "110" => "Bank Jabar dan Banten (Bank BJB)",
            "111" => "Bank DKI Jakarta",
            "112" => "BPD DIY (Yogyakarta)",
            "113" => "Bank Jateng (Jawa Tengah)",
            "114" => "Bank Jatim (Jawa Timur)",
            "115" => "Bank Jambi",
            "116" => "BPD Aceh",
            "117" => "Bank Sumut (Sumatra Utara)",
            "118" => "Bank Nagari (Bank Sumbar)",
            "119" => "Bank Riau Kepri",
            "120" => "Bank Sumsel Babel",
            "121" => "Bank Lampung",
            "122" => "Bank Kalsel (Bank Kalimantan Selatan)",
            "123" => "Bank Kalbar (Bank Kalimantan Barat)",
            "124" => "Bank Kaltimtara (Kalimantan Timur dan Utara)",
            "125" => "Bank Kalteng (Kalimantan Tengah)",
            "126" => "Bank Sulselbar (Sulawesi Selatan dan Barat)",
            "127" => "Bank Sulutgo (Sulawesi Utara dan Gorontalo)",
            "128" => "Bank NTB",
            "129" => "Bank BPD Bali",
            "130" => "Bank NTT",
            "131" => "Bank Maluku Malut",
            "132" => "Bank Papua",
            "133" => "Bank Bengkulu",
            "134" => "Bank Sulteng (Sulawesi Tengah)",
            "135" => "Bank Sultra (Sulawesi Tenggara)",
            "137" => "Bank BPD Banten",

            "003" => "Bank Ekspor Indonesia",
            "019" => "Bank Panin",
            "517" => "Bank Panin Dubai Syariah",
            "020" => "Bank Arta Niaga Kencana",
            "030" => "American Express Bank LTD",
            "032" => "JP Morgan Chase Bank, N.A.",
            "033" => "Bank of America, N.A.",
            "034" => "ING Indonesia Bank",
            "036" => "Bank Multicor",
            "037" => "Bank Artha Graha Internasional",
            "039" => "Bank Credit Agricole Indosuez",
            "040" => "The Bangkok Bank Co. LTD",
            "087" => "Bank HSBC Indonesia",
            "042" => "Mitsubishi UFJ Financial Group (MUFG Bank)",
            "045" => "Bank Sumitomo Mitsui Indonesia",
            "047" => "Bank Resona Perdania",
            "048" => "Bank Mizuho Indonesia",
            "050" => "Standard Chartered Bank",
            "052" => "Bank ABN AMRO",
            "053" => "Bank Keppel Tatlee Buana",
            "054" => "Bank Capital Indonesia",
            "057" => "Bank BNP Paribas Indonesia",
            "059" => "Korea Exchange Bank Danamon",
            "060" => "Rabobank Internasional Indonesia",
            "061" => "Bank ANZ Indonesia",
            "212" => "Bank Woori Saudara",
            "069" => "Bank of China",
            "076" => "Bank Bumi Arta",
            "088" => "Bank Antar Daerah",
            "089" => "Bank Haga",
            "093" => "Bank IFI",
            "095" => "Bank J Trust Indonesia",
            "097" => "Bank Mayapada",
            "145" => "Bank Nusantara Parahyangan",
            "146" => "Bank Swadesi (Bank of India Indonesia)",
            "151" => "Bank Mestika Dharma",
            "152" => "Bank Shinhan Indonesia (Bank Metro Express)",
            "157" => "Bank Maspion Indonesia",
            "159" => "Bank Hagakita",
            "161" => "Bank Ganesha",
            "162" => "Bank Windu Kentjana",
            "164" => "Bank ICBC Indonesia (Halim Indonesia Bank)",
            "166" => "Bank Harmoni International",
            "167" => "Bank QNB Kesawan (Bank QNB Indonesia)",
            "405" => "Bank Swaguna",
            "459" => "Krom Bank (Eks Bank Bisnis Internasional)",
            "466" => "Bank Sri Partha",
            "472" => "Bank Jasa Jakarta",
            "484" => "Bank Hana (Eks Bank Bintang Manunggal)",
            "485" => "Bank MNC Internasional (Bank Bumiputera)",
            "490" => "Bank Yudha Bhakti",
            "491" => "Bank Mitraniaga",
            "494" => "Bank Raya (BRI Agro Niaga)",
            "498" => "Bank SBI Indonesia (Bank Indomonex)",
            "501" => "Bank Royal Indonesia",
            "503" => "Bank National Nobu (Bank Alfindo)",
            "506" => "Bank Mega Syariah",
            "513" => "Bank Ina Perdana",
            "517" => "Bank Harfa",
            "520" => "Prima Master Bank",
            "521" => "Bank Persyarikatan Indonesia",
            "525" => "Bank Akita",
            "526" => "Bank Oke Indonesia (Liman International Bank)",
            "531" => "Anglomas Internasional Bank",
            "523" => "Bank Sahabat Sampoerna (Bank Dipo International)",
            "547" => "Bank Purba Danarta",
            "548" => "Bank Multi Arta Sentosa",
            "553" => "Bank Mayora Indonesia",
            "555" => "Bank Index Selindo",
            "566" => "Bank Victoria International",
            "558" => "Bank Eksekutif",
            "559" => "Centratama Nasional Bank",
            "562" => "Bank Fama Internasional",
            "564" => "Bank Mandiri Taspen Pos (Bank Sinar Harapan Bali)",
            "945" => "Bank Agris (Bank Finconesia)",
            "946" => "Bank Merincorp",
            "949" => "Bank CTBC (China Trust) Indonesia",
            "425" => "Bank BJB Syariah",
            "688" => "BPR KS (Karyajatnika Sedaya)",
            "600" => "BPR Supra Artapersada",
            "028" => "BPR Danagung Abadi",
            "945" => "Bank IBK Indonesia",

            "014" => "Bank BCA (Bank Central Asia)",
            "008" => "Bank Mandiri",
            "009" => "Bank BNI (Bank Negara Indonesia)",
            "427" => "Bank Syariah Indonesia (Eks BNI SYARIAH)",
            "002" => "Bank BRI (Bank Rakyat Indonesia)",
            "451" => "Bank Syariah Indonesia (Eks BSM)",
            "022" => "Bank CIMB Niaga",
            "147" => "Bank Muamalat",
            "213" => "Bank BTPN (Bank Tabungan Pensiunan Nasional)",
            "547" => "Bank BTPN Syariah",
            "422" => "Bank Syariah Indonesia (Eks BRI Syariah)",
            "200" => "Bank Tabungan Negara (Bank BTN)",
            "013" => "Permata Bank",
            "011" => "Bank Danamon",
            "016" => "Bank BII Maybank",
            "426" => "Bank Mega",
            "153" => "Bank Sinar Mas",
            "950" => "Bank Commonwealth",
            "028" => "Bank OCBC NISP",
            "441" => "Bank KB Bukopin",
            "521" => "Bank KB Bukopin Syariah",
            "536" => "Bank BCA Syariah",
            "026" => "Bank Lippo",
            "031" => "Citibank",
            "535" => "SeaBank (Eks Bank Kesejahteraan Ekonomi)",
            "542" => "Bank Jago (Eks Bank Artos Indonesia)",
            "023" => "Bank UOB Indonesia",
            "490" => "Bank Neo Commerce (Akulaku)",
            "567" => "Allo Bank (Eks Bank Harda)",
            "947" => "Bank Aladin Syariah (Eks Bank Maybank Indocorp)",
            "110" => "Bank Jabar dan Banten (Bank BJB)",
            "111" => "Bank DKI Jakarta",
            "112" => "BPD DIY (Yogyakarta)",
            "113" => "Bank JATENG (Jawa Tengah)",
            "114" => "Bank JATIM (Jawa Timur)",
            "115" => "Bank Jambi",
            "118" => "Bank NAGARI (Bank SUMBAR)",
            "121" => "Bank Lampung",
            "122" => "Bank KALSEL (Bank Kalimantan Selatan)",
            "126" => "Bank SULSELBAR (Bank Sulawesi Selatan dan Barat)",
            "129" => "Bank BPD Bali",
            "130" => "Bank NTT",
            "131" => "Bank Maluku MALUT",
            "019" => "Bank Panin",
            "517" => "Bank Panin Dubai Syariah",
            "152" => "Bank SHINHAN Indonesia (Bank Metro Express)",
            "212" => "Bank Woori Saudara",
            "200" => "Bank Tabungan Negara (Bank BTN)",
            "405" => "Bank Swaguna",
            "009" => "Bank BNI (Bank Negara Indonesia)",
            "564" => "Bank Mandiri Taspen Pos (Bank Sinar Harapan Bali)",
            "555" => "Bank Index Selindo",
            "566" => "Bank Victoria International",
            "688" => "BPR KS (Karyajatnika Sedaya)",
            "945" => "Bank Agris (Bank Finconesia)",
            "949" => "Bank CTBC (China Trust) Indonesia",
            "146" => "Bank Swadesi (Bank of India Indonesia)",
            // Tambahan dari listmu tanpa kode yang sudah ada di atas:
            "136" => "Bank Capital", // NNS 93600054, kode dibuat 136 (unik)
            "137" => "Bank Nagari",  // sudah ada 118, jadi 137 tambahan agar unik
            "138" => "Bank Selsulbar", // NNS 93600126
            "139" => "BPDBali",       // NNS 93600129
            "140" => "BPD Maluku & Maluku Utara", // NNS 93600131
            "141" => "Bank QNB Indonesia", // NNS 93600167
            "142" => "BRI Syariah",  // NNS 93600422
            "143" => "BSM",          // NNS 93600451
            "144" => "Hanna Bank",   // NNS 93600484
            "145" => "Bank Sehat Sampoerna", // NNS 93600523
            "148" => "Bank BTPN Syariah", // sudah ada 547, jadi ini duplikat (abaikan)
            "149" => "Superbank",    // tapi ini non-bank, abaikan
            "150" => "Bank Mantap",  // NNS 93600564
            "151" => "Finnet",      // non-bank, abaikan
            "152" => "Bank Eka",    // NNS 93600690
        ];

        $qris = [
            "93600002" => "Bank BRI (Bank Rakyat Indonesia)",
            "93600008" => "Bank Mandiri",
            "93600009" => "Bank BNI (Bank Negara Indonesia)",
            "93600011" => "Bank Danamon",
            "93600013" => "Permata Bank",
            "93600014" => "Bank BCA (Bank Central Asia)",
            "93600019" => "Bank Panin",
            "93600022" => "Bank CIMB Niaga",
            "93600023" => "Bank UOB Indonesia",
            "93600028" => "Bank OCBC NISP",
            "93600054" => "Bank Capital",
            "93600110" => "Bank Jabar dan Banten (Bank BJB)",
            "93600111" => "Bank DKI Jakarta",
            "93600112" => "BPD DIY (Yogyakarta)",
            "93600113" => "Bank JATENG (Jawa Tengah)",
            "93600114" => "Bank JATIM (Jawa Timur)",
            "93600115" => "Bank Jambi",
            "93600118" => "Bank Nagari (Bank SUMBAR)",
            "93600121" => "Bank Lampung",
            "93600122" => "Bank KALSEL (Bank Kalimantan Selatan)",
            "93600126" => "Bank SULSELBAR (Bank Sulawesi Selatan dan Barat)",
            "93600129" => "Bank BPD Bali",
            "93600130" => "Bank NTT",
            "93600131" => "Bank Maluku & Maluku Utara",
            "93600146" => "Bank Swadesi (Bank of India Indonesia)",
            "93600147" => "Bank Muamalat",
            "93600152" => "Bank SHINHAN Indonesia (Bank Metro Express)",
            "93600167" => "Bank QNB Indonesia",
            "93600200" => "Bank Tabungan Negara (Bank BTN)",
            "93600212" => "Bank Woori Saudara",
            "93600213" => "Bank BTPN (Jenius)",
            "93600422" => "Bank Syariah Indonesia (Eks BRI Syariah)",
            "93600426" => "Bank Mega",
            "93600451" => "Bank Syariah Indonesia (Eks BSM)",
            "93600484" => "Bank Hana (Eks. Bank Bintang Manunggal)",
            "93600490" => "Bank Neo Commerce (Akulaku)",
            "93600501" => "Bank Digital BCA",
            "93600517" => "Bank Panin Dubai Syariah",
            "93600523" => "Bank Sahabat Sampoerna (Bank Dipo International)",
            "93600535" => "SeaBank (Eks Bank Kesejahteraan Ekonomi)",
            "93600547" => "Bank BTPN Syariah",
            "93600555" => "Bank Index Selindo",
            "93600564" => "Bank Mantap",
            "93600566" => "Bank Victoria International",
            "93600567" => "Allo Bank (Eks Bank Harda)",
            "93600690" => "Bank Eka",
            "93600947" => "Bank Aladin Syariah (Eks Bank Maybank Indocorp)",
            "93600949" => "Bank CTBC Indonesia",
            "93600950" => "Bank Commonwealth",
            "93600000" => "Jalin",
            "93600016" => "GOPAY",
            "93600137" => "Jawara Mobile",
            "93600153" => "Sinarmas",
            "93600485" => "Motion Banking",
            "93600503" => "Nobu",
            "93600562" => "Superbank",
            "93600777" => "Finnet",
            "93600808" => "bayarind",
            "93600811" => "Ottocash",
            "93600812" => "Kaspro",
            "93600814" => "Netzme",
            "93600815" => "Bimasakti",
            "93600816" => "SPIN (MNC)",
            "93600817" => "Yukk",
            "93600818" => "Paydia",
            "93600822" => "Astrapay",
            "93600825" => "Zipay",
            "93600831" => "INACASH",
            "93600835" => "Virgo",
            "93600836" => "Nusapay",
            "93600838" => "Dutamoney",
            "93600845" => "Pakai Donk",
            "93600848" => "xendit",
            "93600849" => "Paylabs",
            "93600898" => "TMoney",
            "93600899" => "Doku",
            "93600911" => "LinkAja",
            "93600912" => "OVO",
            "93600914" => "GOPAY",
            "93600915" => "Dana",
            "93600916" => "Gudang Voucher",
            "93600917" => "Paytren",
            "93600918" => "Shopeepay",
            "93600919" => "Bluepay",
            "93600920" => "Isaku",
            "93600921" => "Saldomu",
            "93600923" => "Yourpay",
            "93600998" => "QRIS DSP",
        ];

        // Insert bank providers dan channels tanpa cek duplikasi
        foreach ($banks as $code => $name) {
            // Cek apakah provider sudah ada (berdasarkan kode atau nama)
            $provider = DB::table('providers')->where('name', $name)->first();

            if (!$provider) {
                $providerId = DB::table('providers')->insertGetId([
                    'name' => $name,
                    'provider_code' => $code,
                    'provider_type' => 'bank',
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            } else {
                $providerId = $provider->id;
            }

            DB::table('channels')->insert([
                'channel_code' => $code,
                'channel_type' => 'transfer',
                'provider_id' => $providerId,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        // Insert qris providers dan channels tanpa cek duplikasi, tapi jika sudah ada, ambil provider id-nya
        foreach ($qris as $code => $name) {
            // Cek apakah provider sudah ada berdasarkan kode
            $provider = DB::table('providers')->where('name', $name)->first();

            if (!$provider) {
                $providerId = DB::table('providers')->insertGetId([
                    'name' => $name,
                    'provider_code' => $code,
                    'provider_type' => 'qris',
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            } else {
                $providerId = $provider->id;
            }

            DB::table('channels')->insert([
                'channel_code' => $code,
                'channel_type' => 'qris',
                'provider_id' => $providerId,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
